name = "sink"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-04-07"
upload_source_maps = true
pages_build_output_dir = "./dist"

[dev]
port = 3000

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "KV"
id = "967516deed7145218faae26e4859c412"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "sink"